# Generated by Django 5.1.5 on 2025-01-18 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='menu',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['-published'], name='menu_menu_publish_eee2bb_idx'),
        ),
    ]
